Feature/train model
jakub1090cn/BaldOrNot pull request #15
Opened 2024-08-28 17:07 UTC by jakub1090cn

## Description

## Testing

## Types of Changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Tests update
- [ ] Documentation update
- [ ] Changes that do not directly affect the source code or tests

## Checklist
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Additional Comments

## Screenshots (if appropriate)

2024-08-28 18:03 UTC, skrzypczykt commented on src/data.py
> +    def on_epoch_end(self):
remove

2024-08-28 18:10 UTC, skrzypczykt requested changes

2024-08-28 18:10 UTC, skrzypczykt commented on src/data.py
> +        indexes = self.indexes[index * self.batch_size:(index + 1) * self.batch_size]
remove

2024-08-28 18:10 UTC, skrzypczykt commented on src/model_training.py
> +    num_samples = 100
move inside mockDataset

2024-08-28 18:10 UTC, skrzypczykt commented on src/model_training.py
> +
Callbacks, validation data - same data, history = model.fit, make this function return sth

2024-09-02 21:36 UTC, jakub1090cn commented
The training script has been updated with the elements mentioned above.

2024-09-05 17:30 UTC, skrzypczykt commented on tests/test_train_model_integration.py
> +    MockFit.assert_called_once()
Liczba epok zgodna z liczbą linii w history.

Sprawdzenie czy są logi z Tensorboarda,

Czy model sie zapisał?

(ewentualnie) 'EarlyStopping' - sprawdzać czy najlepsze wyniki są z epoki 4 od konca

2024-09-05 17:30 UTC, skrzypczykt approved these changes

2024-09-12 17:15 UTC, skrzypczykt commented on src/model_training.py
> +    current_training = f"training{current_date}"
move 'training' to arguments

2024-09-12 17:16 UTC, skrzypczykt commented on scripts/train.py
> +    print("Start training:")
use logger

2024-09-12 17:26 UTC, skrzypczykt commented on src/model_training.py
> +        )
Create a decorator: https://blog.hubspot.com/website/decorators-in-python
put it in utils

2024-09-12 17:28 UTC, skrzypczykt commented on src/plot.py
> +) -> None:
rename metric to metric_name

2024-09-12 17:29 UTC, skrzypczykt commented on src/plot.py
> +            "is initialized.".format(LOG_FILE_NAME, output_dir_path)
decorate

2024-09-12 17:34 UTC, skrzypczykt commented on tests/test_train_model_integration.py
> +    log_dir = "tensorboard_logs_test"
log_dir =test_config[...]

2024-09-12 17:36 UTC, skrzypczykt commented on tests/test_train_model_integration.py
> +    assert len(log_files) > 0, "Log directory is empty"
weird

2024-09-12 17:37 UTC, skrzypczykt reviewed
great

2024-09-16 14:13 UTC, raodz approved these changes
lgtm

2024-09-16 14:16 UTC, merged